homeassistant:
#  name:
#  latitude:
#  longitude:
#  elevation: 50
  unit_system: metric
  time_zone: Europe/Kiev
  packages: !include_dir_merge_named includes/packages
  customize: !include customize.yaml
#  auth_providers:
#    - type: trusted_networks
#      trusted_networks:
#        - 192.168.0.0/24
#        - fd00::/8
  #      - 192.168.0.1/24
#        - 192.168.0.109
#        - 172.30.33.0/24
#        - 172.30.32.0/23
#        - 172.17.0.0/16
#        - 172.30.33.0
#        - 134.249.143.65
#      allow_bypass_login: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
#    - 172.30.32.0/24
#    - 172.16.0.0/16

lovelace: !include lovelace.yaml

mqtt: !include configuration/mqtt.yaml

default_config:

tts:
  - platform: google_translate

logger:
  default: warning
  logs:
    homeassistant.helpers.entity: error
    homeassistant.components.vacuum: error

#zone:
#  - name: Home
#    latitude:
#    longitude:
#    radius: 70
#    icon: mdi:account-multiple

#frontend:
#  themes: !include_dir_merge_named themes

#device_tracker: !include configuration/device_tracker.yaml

#person: !include configuration/person.yaml

#telegram_bot:
#  - platform: polling
#    api_key:
#    allowed_chat_ids:

#notify:
#  - name: telegram_id_1
#    platform: telegram
#    chat_id:
#  - name: telegram_id_2
#    platform: telegram
#    chat_id:

#duckdns: !include configuration/duckdns.yaml


















timer: !include includes/timer.yaml
recorder: !include configuration/recorder.yaml

input_boolean: !include includes/input/input_boolean.yaml
input_select: !include includes/input/input_select.yaml
input_number: !include includes/input/input_number.yaml
input_datetime: !include includes/input/input_datetime.yaml
input_text: !include includes/input/input_text.yaml

sensor: !include_dir_merge_list includes/sensor
binary_sensor: !include_dir_merge_list includes/binary_sensor


automation: !include_dir_merge_list includes/automations
script: !include_dir_merge_named includes/scripts
scene: !include includes/scenes.yaml


switch: !include configuration/switch.yaml
light: !include configuration/light.yaml
group: !include includes/groups.yaml


























#
